version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      dependencies:
        patterns:
          - "*"
